'use client'
import './global.css';
import { GoogleTagManager, GoogleAnalytics } from '@next/third-parties/google'
import { Provider } from 'react-redux';
import { store} from './redux/store';
import Head from 'next/head';

// export const metadata = {
//   title: 'Welcome to daev',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
    <html lang="en">
    <Head>
        <title>'Welcome to daev'</title>
      </Head>
       <GoogleTagManager gtmId="GTM-K5PFW7FW" />
       <GoogleAnalytics gaId="G-7LTKWZT49T" />
      <body>{children}</body>
    </html>
    </Provider>
  );
}
