import './global.css';
import { GoogleTagManager } from '@next/third-parties/google'

export const metadata = {
  title: 'Welcome to daev',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <GoogleTagManager gtmId="GTM-K5PFW7FW" />
      <body>{children}</body>
    </html>
  );
}
